<<<<<<< HEAD
version: '3.8'
=======
>>>>>>> 822c0577ddf5c237c94c95daa7def3142a206478
services:
  backend:
    build: ./backend
    ports:
<<<<<<< HEAD
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth-service
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
=======
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdbname
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
>>>>>>> 822c0577ddf5c237c94c95daa7def3142a206478

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
<<<<<<< HEAD

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
=======
    restart: unless-stopped
>>>>>>> 822c0577ddf5c237c94c95daa7def3142a206478

volumes:
  mongo-data: