services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdbname
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: